service: wistia-video-links

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  lambdaHashingVersion: 20201221
  runtime: nodejs12.x
  profile: nickyiliwang
  memorySize: 256
  apiGateway:
    shouldStartNameWithService: true
  stage: ${opt:stage, 'dev'}
  environment:
    VIDEOS_TABLE_NAME: ${self:custom.WistiaVideosTable.name}
  iamRoleStatements:
    - ${file(iam/WistiaVideosTableIAM.yml):WistiaVideosTableIAM}

resources:
  Resources:
    WistiaVideosTable: ${file(resources/WistiaVideosTable.yml):WistiaVideosTable}

functions:
  addItem:
    handler: src/handlers/addItem.handler
    events:
      - http:
          method: POST
          path: /add
          cors: true

  getItems:
    handler: src/handlers/getItems.handler
    events:
      - http:
          method: GET
          path: /items
          cors: true

custom:
  WistiaVideosTable:
    name: !Ref WistiaVideosTable
    arn: !GetAtt WistiaVideosTable.Arn