service:
  name: simple-list

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
    # setting an .ENV for createTodos and more to use table name in custom
  environment:
    TODOS_TABLE_NAME: ${self:custom.TodosTable.name}
  iamRoleStatements:
    - ${file(iam/TodosTableIAM.yml):TodosTableIAM}

resources:
  Resources:
    TodosTable: ${file(resources/TodosTable.yml):TodosTable}

functions:
  addItem:
    handler: src/handlers/addItem.handler
    events:
      - http:
          method: POST
          path: /add
          cors: true

  getItems:
    handler: src/handlers/getItems.handler
    events:
      - http:
          method: GET
          path: /items
          cors: true

custom:
  TodosTable:
    name: !Ref TodosTable
    arn: !GetAtt TodosTable.Arn